### PR TITLE
Feature/custom event

### PR DESCRIPTION
**Pull request by jaredrethman**
### Description of the Change

Reference this issue #31. Adds ability to listen for changes to Post Finder outside of the plugin.

### Benefits

Users will be able to react to Post Finder updates.

### Possible Drawbacks

None

### Verification Process

In a project I am working on the Post Finder is used within a legacy metabox in the Gutenberg Block Editor. I needed to be able to listen for changes within the theme to have a Block react to changes made when interacting with the Post Finder.

Example:
```jsx

const updateIds = ( e ) => {
	setIds( e.detail.ids );
}

useEffect( () => {
	window.addEventListener( 'updatePostFinder', updateIds );
	return () => {
		window.removeEventListener( 'updatePostFinder', updateIds );
	}
}, [] );

```

### Checklist:

- [x] I have read the [**CONTRIBUTING**](/CONTRIBUTING.md) document.
- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have added tests to cover my change.
- [x] All new and existing tests passed.

### Applicable Issues

#31 

### Changelog Entry

* Added CustomEvent and associated EI11 polyfill to listen for changes outside of the plugin.
* Update `grunt-sass` package version to v2.1.

### CODE REVIEW

**Comment by jaredrethman** [comment]
> LGTM!

"Lets Get This Merge" ;)

**Comment by nicholasio** [comment]
@jaredrethman Can you please update the comper.json version to 0.4.0 as well?

@jeffpaul I'm fine getting this merged (once composer.json is updated). Since we're publishing this plugin I don't think there's anything else needed besides merging.

**Comment by jeffpaul** [comment]
@nicholasio FYI that we've been removing the version from `composer.json` [per guidance from the Composer team](https://getcomposer.org/doc/04-schema.md#version).  We should definitely ensure its updated in `package.json` and `post-finder.php` (as well as `post-finder.pot` if we're actually tracking additional language files).

**Comment by nicholasio** [comment]
@jeffpaul sounds good to me, we can remove it.

**Pull request merged**
